SELECT P1.NUM_PRODUCTEUR, P1.NOM
FROM PRODUCTEURS P1
WHERE P1.NUM_PRODUCTEUR <> 35
      AND NOT EXISTS
      (SELECT *
      FROM RECOLTES R1
      WHERE R1.PRODUCTEUR = 35
      	    AND NOT EXISTS
      	    (SELECT *
	    FROM RECOLTES R2
	    WHERE R1.VIN = R2.VIN
		  AND P1.NUM_PRODUCTEUR = R2.PRODUCTEUR
            )
       )
;
