SELECT IDS, COUNT(NOMINV)
FROM PARTICIPER
GROUP BY IDS
HAVING COUNT(NOMINV) = (SELECT MIN(S.COUNT)
       		       FROM    (SELECT COUNT(NOMINV)
		       	       FROM PARTICIPER
		       	       GROUP BY IDS) S
			       ) ;
