SELECT I.NOM
FROM INVITES I
WHERE NOT EXISTS (SELECT S.*
      	  	 FROM SOIREES S
		 WHERE NOT EXISTS (SELECT P.*
		       	   	  FROM PARTICIPER P
				  WHERE P.IDS = S.IDS
				  	AND P.NOMINV = I.NOM)
					)
;
