SELECT O1.DATE, COUNT(PC1.NOMPART)
FROM ORGANISEPAR O1, ORGANISEPAR O2, PARTICIPERCOMPET PC1, PARTICIPERCOMPET PC2
WHERE O1.IDC = PC2.IDC
      AND O2.IDC = PC2.IDC
      AND O1.DATE = O2.DATE
      AND PC1.NOMPART = PC2.NOMPART
      AND PC1.IDC < PC2.IDC
GROUP BY O1.DATE
