SELECT IDC, COUNT(NOMPART)
FROM PARTICIPERCOMPET 
GROUP BY IDC
HAVING COUNT(NOMPART) = (SELECT MIN(S.count)
       		        FROM 	(SELECT COUNT(NOMPART)
				FROM PARTICIPERCOMPET
				GROUP BY IDC) S
				)
;
