SELECT P.NOM
FROM PARTICIPANTS P
WHERE NOT EXISTS (SELECT C.*
      	  	 FROM COMPETITIONS C
		 WHERE NOT EXISTS (SELECT PC.*
		       	   	  FROM PARTICIPERCOMPET PC
				  WHERE PC.IDC = C.IDC
				  	AND PC.NOMPART = P.NOM)
					)
;
