/* Generated By:JavaCC: Do not edit this line. AnalyseurSyntaxiqueConstants.java */
package fr.insarouen.iti.prog.aventure.data.fichier.compilation.Analyseurs;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyseurSyntaxiqueConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARAG = 6;
  /** RegularExpression Id. */
  int PARAD = 7;
  /** RegularExpression Id. */
  int VIRG = 8;
  /** RegularExpression Id. */
  int AFF = 9;
  /** RegularExpression Id. */
  int CHAINE = 10;
  /** RegularExpression Id. */
  int NOMFONCTION = 11;
  /** RegularExpression Id. */
  int NOMBRE = 12;
  /** RegularExpression Id. */
  int ENUM = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int CDC = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "<VIRG>",
    "\"=\"",
    "<CHAINE>",
    "<NOMFONCTION>",
    "<NOMBRE>",
    "<ENUM>",
    "<ID>",
    "<CDC>",
  };

}
