/* Generated By:JavaCC: Do not edit this line. AnalyseurSyntaxique.java */
package fr.insarouen.iti.prog.aventure.data.fichier.compilation.Analyseurs;

import java.util.ArrayList;
import java.util.List;

import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.DeclarationMultiple;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.DeclarationSimple;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.ArgumentSimple;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.Fonction;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.SuiteArguments;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.Identifiant;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.EnumerationCDF;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.ChaineDeCaracteres;
import fr.insarouen.iti.prog.aventure.data.fichier.compilation.AST.Nombre;

public class AnalyseurSyntaxique implements AnalyseurSyntaxiqueConstants {

  final public DeclarationMultiple declarationMultiple() throws ParseException {
         DeclarationSimple ds = null;
  List<DeclarationSimple> lds = new ArrayList<DeclarationSimple>();
    label_1:
    while (true) {
      ds = declarationSimple();
                             lds.add(ds);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
     {if (true) return new DeclarationMultiple(lds);}
    throw new Error("Missing return statement in function");
  }

  final public DeclarationSimple declarationSimple() throws ParseException {
         DeclarationSimple res=null;
  Identifiant idtf = null;
  Fonction laFonction = null;
    idtf = identifiant();
    jj_consume_token(AFF);
    laFonction = fonction();
     {if (true) return new DeclarationSimple(idtf, laFonction);}
    throw new Error("Missing return statement in function");
  }

  final public Fonction fonction() throws ParseException {
         SuiteArguments lesArgs;
  String sonNom = null;
    sonNom = nomFonction();
    jj_consume_token(PARAG);
    lesArgs = suiteArguments();
    jj_consume_token(PARAD);
   {if (true) return new Fonction(sonNom, lesArgs);}
    throw new Error("Missing return statement in function");
  }

  final public SuiteArguments suiteArguments() throws ParseException {
  ArgumentSimple unArg = null;
  List<ArgumentSimple> lArg = new ArrayList<ArgumentSimple>();
    unArg = argumentSimple();
                             lArg.add(unArg);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(VIRG);
      unArg = argumentSimple();
                                      lArg.add(unArg);
    }
    {if (true) return new SuiteArguments(lArg);}
    throw new Error("Missing return statement in function");
  }

  final public ArgumentSimple argumentSimple() throws ParseException {
         ArgumentSimple res = null;
  Token t = null;
  Fonction f = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOMBRE:
      t = jj_consume_token(NOMBRE);
                  res = new Nombre(t.image);
      break;
    case ENUM:
      t = jj_consume_token(ENUM);
               res = new EnumerationCDF(t.image);
      break;
    case NOMFONCTION:
      f = fonction();
                   res = f;
      break;
    case ID:
      t = jj_consume_token(ID);
             res = new Identifiant(t.image);
      break;
    case CHAINE:
      t = jj_consume_token(CHAINE);
                 res = new ChaineDeCaracteres(t.image.substring(1, t.image.length() - 1));
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

// Terminaux 
  final public String nomFonction() throws ParseException {
         Token t=null;
    t = jj_consume_token(NOMFONCTION);
     {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public Identifiant identifiant() throws ParseException {
         Token t = null;
    t = jj_consume_token(ID);
                   {if (true) return new Identifiant(t.image);}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public AnalyseurSyntaxiqueTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4000,0x100,0x7c00,};
   }

  /** Constructor with InputStream. */
  public AnalyseurSyntaxique(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalyseurSyntaxique(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new AnalyseurSyntaxiqueTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public AnalyseurSyntaxique(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AnalyseurSyntaxiqueTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public AnalyseurSyntaxique(AnalyseurSyntaxiqueTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AnalyseurSyntaxiqueTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[16];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 16; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
