CREATE TABLE Monde(
	nomMonde VARCHAR(20) PRIMARY KEY
	);	
	
CREATE TABLE Porte(
	nomPorte VARCHAR(20) PRIMARY KEY, 
	etat VARCHAR(11) CHECK (etat IN('FERME','OUVERT','VEROUILLE','DEVEROUILLE')), 
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde) ON DELETE CASCADE
	); 

CREATE TABLE Piece(
	nomPiece VARCHAR(20) PRIMARY KEY,
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde) ON DELETE CASCADE
	);
	
CREATE TABLE PiedDeBiche(
	nomPDB VARCHAR(20) PRIMARY KEY, 
	estDeplacabe BOOL, 
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde) ON DELETE CASCADE
	);
	
CREATE TABLE JoueurHumain(
	nomJoueur VARCHAR(20) PRIMARY KEY, 
	pointVie INTEGER CHECK (pointVie >= 0), 
	pointForce INTEGER CHECK (pointForce >= 0), 
	nomPiece VARCHAR(20) REFERENCES Piece(nomPiece) ON DELETE CASCADE,
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde) ON DELETE CASCADE
	);
	
CREATE TABLE PossedePorte(
	nomPorte VARCHAR(20) REFERENCES Porte(nomPorte) ON DELETE CASCADE, 
	nomPiece VARCHAR(20) REFERENCES Piece(nomPiece) ON DELETE CASCADE,
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde)	ON DELETE CASCADE
	);
	
CREATE TABLE ContientPDB(
	nomPDB VARCHAR(20) REFERENCES PiedDeBiche(nomPDB) ON DELETE CASCADE, 
	nomPiece VARCHAR(20) REFERENCES Piece(nomPiece) ON DELETE CASCADE,
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde) ON DELETE CASCADE	
	);
	
CREATE TABLE PossedePDB(
	nomPDB VARCHAR(20) REFERENCES PiedDeBiche(nomPDB) ON DELETE CASCADE, 
	nomJoueur VARCHAR(20) REFERENCES JoueurHumain(nomJoueur) ON DELETE CASCADE,
	nomMonde VARCHAR(20) REFERENCES Monde(nomMonde)	ON DELETE CASCADE
	);
