DROP TABLE T;

CREATE TABLE T (
A INTEGER NOT NULL,
B INTEGER NOT NULL); 

INSERT INTO T VALUES (0,0);
INSERT INTO T VALUES (2,3);
INSERT INTO T VALUES (0,1);

 * à modifier* GRANT select, update, insert, delete ON T to grtti;
