DROP TABLE T;

CREATE TABLE T (
A INTEGER NOT NULL,
B INTEGER NOT NULL); 

INSERT INTO T VALUES (-1,6);
INSERT INTO T VALUES (-1,12);
INSERT INTO T VALUES (5,8);
INSERT INTO T VALUES (5,3);
INSERT INTO T VALUES (5,3);


 * à modifier* GRANT select, update, insert, delete ON T to grtti;
