SELECT P1.NUM_PRODUCTEUR, COUNT(DISTINCT V1.CRU)
FROM VINS V1, PRODUCTEURS P1, RECOLTES R1
WHERE R1.VIN = V1.NUM_VIN
      AND R1.PRODUCTEUR = P1.NUM_PRODUCTEUR
      AND V1.CRU IN
      	  (SELECT V2.CRU
	  FROM VINS V2, RECOLTES R2
	  WHERE R2.VIN = V2.NUM_VIN
	  	AND R2.PRODUCTEUR = P1.NUM_PRODUCTEUR
	  GROUP BY V2.CRU
	  HAVING SUM(R2.QUANTITE) > 200)
GROUP BY NUM_PRODUCTEUR;
