SELECT NOM, PRENOM
FROM PRODUCTEURS
WHERE NOT EXISTS
      (SELECT *
      FROM VINS
      WHERE NOT EXISTS
      	    (SELECT *
	    FROM RECOLTES
	    WHERE PRODUCTEUR = NUM_PRODUCTEUR
	    	  AND VIN = NUM_VIN
	    )
      )
;
